version: "3.8"

services:
  notes:
    build:
      context: .
    ports:
      - 8000:8000
      - 9229:9229
    environment:
      - SERVER_PORT=8000
      - CONNECTION_STRING=mongodb://mongodb:27017/notes
    volumes:
      - ./:/app
    command: node server.js

  mongo:
    image: mongo:4.2.9
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
